#Q1: Build Your Personalized Knowledge Base:

In [1]:
import pandas as pd
import numpy as np
fixed_entries = [
    {"question": "what is the annual fee", "answer": "The annual fee is Rs 500.",
     "keywords": "fee cost price charge", "category": "billing"},

    {"question": "how to reset password", "answer": "Go to Settings > Reset Password.",
     "keywords": "password reset login", "category": "account"},

    {"question": "what are your working hours", "answer": "We are open 9 AM to 5 PM.",
     "keywords": "hours timing open time", "category": "general"},

    {"question": "how can i pay the fee", "answer": "You can pay via UPI, card, or net banking.",
     "keywords": "pay payment upi fee", "category": "billing"},
]
roll = 1024170310
d = [digit for digit in str(roll)[-2:]]
cat = ['billing','account','general']
cat_main=[]
for i in d:
  cat_main.append(cat[int(i)%3])
questions = [
    "how do i change my email",
    "how can i contact support"
]

answers = [
    "Go to Settings > Account > Change Email.",
    "You can contact support through the Help Center or email us."
]

keywords = [
    "email change account settings",
    "support help contact"
]
newFqa=[]
for i in range(2):
  newFqa.append({"question": questions[i],"answer":answers[i],"keywords":keywords[i],"category":cat_main[i]})
newFqa.extend(fixed_entries)
newFqa

[{'question': 'how do i change my email',
  'answer': 'Go to Settings > Account > Change Email.',
  'keywords': 'email change account settings',
  'category': 'account'},
 {'question': 'how can i contact support',
  'answer': 'You can contact support through the Help Center or email us.',
  'keywords': 'support help contact',
  'category': 'billing'},
 {'question': 'what is the annual fee',
  'answer': 'The annual fee is Rs 500.',
  'keywords': 'fee cost price charge',
  'category': 'billing'},
 {'question': 'how to reset password',
  'answer': 'Go to Settings > Reset Password.',
  'keywords': 'password reset login',
  'category': 'account'},
 {'question': 'what are your working hours',
  'answer': 'We are open 9 AM to 5 PM.',
  'keywords': 'hours timing open time',
  'category': 'general'},
 {'question': 'how can i pay the fee',
  'answer': 'You can pay via UPI, card, or net banking.',
  'keywords': 'pay payment upi fee',
  'category': 'billing'}]

In [2]:
df = pd.DataFrame(newFqa)
df

,question,answer,keywords,category
0,how do i change my email,Go to Settings > Account > Change Email.,email change account settings,account
1,how can i contact support,You can contact support through the Help Cente...,support help contact,billing
2,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
3,how to reset password,Go to Settings > Reset Password.,password reset login,account
4,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
5,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing

Q2: Generate and Score a Hypothesis - Implement a scoring function that takes a query string and returns all matching entries ranked by confidence

In [3]:
def scoring(query,df):
  questions = [sent.lower().split() for sent in df['question']]
  actual = query.lower().split()
  order = []
  for i in range(len(questions)):
    cnt = 0
    for w in actual:
      if(w in questions[i]):
        cnt+=1
    order.append(cnt)
  sorted_order = np.argsort(order)
  ans =[]
  for i in range(len(order)):
    ans.append(df['question'][sorted_order[i]])
  return ans

In [4]:
print("Please enter a query")
query = input()
ranked_FAQ = scoring(query,df)
print("Here are FAQ's in sorted order -> (increasing order of matching)")
print(ranked_FAQ)

Please enter a query
how email change
Here are FAQ's in sorted order -> (increasing order of matching)
['what is the annual fee', 'what are your working hours', 'how to reset password', 'how can i contact support', 'how can i pay the fee', 'how do i change my email']

Q3: Write a function same_category(category_name, df) that returns all questions belonging to a given category. Call it using the category of one of the personalized entries from Q1, and print the result.

In [5]:
def same_category(category_name,df):
    l = df.groupby('category')['question'].apply(list)
    return l[category_name]

In [6]:
print(same_category(cat_main[0],df))

['how do i change my email', 'how to reset password']

Q4: Pick any one entry in your knowledge base. Ask the user to input a new keyword, add it to that entry's keywords, and save your entire updated DataFrame to a CSV file named <your_roll_number>_faq_data.csv.

In [7]:
key = input("Please Enter new Keyword for question 1 : ")
df.loc[0,'keywords']+=" " + key.lower()
df.to_csv('1024170310_faq_data.csv', index=False)

Please Enter new Keyword for question 1 : Urgent

In [8]:
df_new = pd.read_csv('1024170310_faq_data.csv');
df_new

,question,answer,keywords,category
0,how do i change my email,Go to Settings > Account > Change Email.,email change account settings urgent,account
1,how can i contact support,You can contact support through the Help Cente...,support help contact,billing
2,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
3,how to reset password,Go to Settings > Reset Password.,password reset login,account
4,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
5,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing

Q5: Using groupby, print how many FAQ entries you have per category.

In [9]:
print(df.groupby('category')['question'].count())

category
account    2
billing    3
general    1
Name: question, dtype: int64

Q6: Modify your Q2 scoring function so that if two or more entries tie for the highest score, it does not silently pick one — it prints all matching entries instead, so the user can see every equally good match. Demonstrate with one query that produces a tie (e.g. a query matching both "fee" entries) and one that doesn't.

In [10]:
def scoring(query,df):
  questions = [sent.lower().split() for sent in df['question']]
  actual = query.lower().split()
  order = []
  for i in range(len(questions)):
    cnt = 0
    for w in actual:
      if(w in questions[i]):
        cnt+=1
    order.append(cnt)
  ans ={}
  for i in range(len(order)):
        if order[i] not in ans:
            ans[order[i]] = []

        ans[order[i]].append(df['question'][i])
  max_score = max(order)
  print("Highest score:", max_score)
  print("Matching questions:")
  for question in ans[max_score]:
      print(question)

  return ans

In [11]:
print("Please enter a query")
query = input()
ranked_FAQ = scoring(query,df)
print("Here are FAQ's in sorted order -> (increasing order of matching)")
print(ranked_FAQ)

Please enter a query
fee
Highest score: 1
Matching questions:
what is the annual fee
how can i pay the fee
Here are FAQ's in sorted order -> (increasing order of matching)
{0: ['how do i change my email', 'how can i contact support', 'how to reset password', 'what are your working hours'], 1: ['what is the annual fee', 'how can i pay the fee']}

In [12]:
print("Please enter a query")
query = input()
ranked_FAQ = scoring(query,df)
print("Here are FAQ's in sorted order -> (increasing order of matching)")
print(ranked_FAQ)

Please enter a query
password
Highest score: 1
Matching questions:
how to reset password
Here are FAQ's in sorted order -> (increasing order of matching)
{0: ['how do i change my email', 'how can i contact support', 'what is the annual fee', 'what are your working hours', 'how can i pay the fee'], 1: ['how to reset password']}